#!/usr/bin/env python3
"""Prepare the post-route gate-level simulation (GLS) of orbit_demo.

From the routed netlist (ORFS 6_final.v) this writes, into --out-dir:

  orbit_demo_gl.v   the netlist with its top module renamed to orbit_demo_gl,
                    so it can be simulated next to the RTL orbit_demo;
  gl_inject.vh      a task flip_copy(k) that inverts redundant storage bit k
                    (k = 0 .. N_REDUNDANT_BITS-1) in BOTH models at once: the
                    RTL register bit and the state of the corresponding
                    flip-flop cell in the netlist, plus flip_kind(k) (0 = one
                    of the duplicated accumulator/result copies, 1 = one of the
                    three thermal copies).

The netlist flip-flops are found by name, the same way pd/audit_storage.py
does; a missing or ambiguous cell is an error, so the GLS cannot silently
skip a copy that synthesis merged away.
"""

import argparse
import os
import re
import sys

LANES = 4


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--netlist", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--state", default="IQ", help="name of the flip-flop state reg in the cell models")
    ap.add_argument("--liberty", help="liberty file: only cells with an ff group count as flip-flops "
                    "(needed where the flow adds other cells with derived names, e.g. tie cells)")
    a = ap.parse_args()

    text = open(a.netlist, encoding="utf-8").read()
    n = len(re.findall(r'^module\s+orbit_demo\s*\(', text, re.M))
    if n != 1:
        sys.exit(f"gen_gls: expected one 'module orbit_demo (' in {a.netlist}, found {n}")
    os.makedirs(a.out_dir, exist_ok=True)
    with open(os.path.join(a.out_dir, "orbit_demo_gl.v"), "w") as f:
        f.write(re.sub(r'^module\s+orbit_demo\s*\(', 'module orbit_demo_gl (', text, count=1, flags=re.M))

    # Every instance with an escaped name: "<celltype> \<escaped name> (".
    insts = re.findall(r'^\s*(\S+)\s+\\(\S+)\s+\(', text, re.M)
    if a.liberty:
        sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
        from audit_storage import liberty_sequential_cells
        ffs, _latches = liberty_sequential_cells(a.liberty)
        insts = [(ct, nm) for (ct, nm) in insts if ct in ffs]
    names = [nm for (_ct, nm) in insts]

    def find(prefix):
        hits = [nm for nm in names if nm.startswith(prefix + "$")]
        if len(hits) != 1:
            sys.exit(f"gen_gls: {len(hits)} cells for {prefix} in {a.netlist}")
        return hits[0]

    targets = []  # (kind, rtl_ref, gl_ref)
    for lane in range(LANES):
        for reg in ("u_acc_a", "u_acc_b", "u_res_a", "u_res_b"):
            for bit in range(32):
                gl = find(f"g_lane[{lane}].u_lane.{reg}/q[{bit}]")
                targets.append((0, f"rtl.g_lane[{lane}].u_lane.{reg}.q[{bit}]", gl))
    for cp in ("u_copy0", "u_copy1", "u_copy2"):
        for bit in range(2):
            gl = find(f"u_thermal.{cp}/q[{bit}]")
            targets.append((1, f"rtl.u_thermal.{cp}.q[{bit}]", gl))

    lines = ["// Generated by pd/gls/gen_gls.py from " + os.path.basename(a.netlist) + "; do not edit.",
             f"localparam integer N_REDUNDANT_BITS = {len(targets)};",
             f"localparam integer N_DUP_BITS = {sum(1 for t in targets if t[0] == 0)};",
             f"localparam integer N_TMR_BITS = {sum(1 for t in targets if t[0] == 1)};",
             "// Targets 0 .. N_DUP_BITS-1 are duplicated copies, the rest thermal copies.",
             "",
             "// Invert redundant storage bit k in the RTL and in the routed netlist.",
             "task flip_copy(input integer k);",
             "    begin",
             "        case (k)"]
    for k, (_kind, rtl, gl) in enumerate(targets):
        g = f"gl.\\{gl} .{a.state}"
        lines.append(f"        {k}: begin {rtl} = ~{rtl}; {g} = ~{g}; end")
    lines += ["        default: begin $display(\"flip_copy: bad index %0d\", k); $finish; end",
              "        endcase",
              "    end",
              "endtask",
              "",
              "// 0: duplicated accumulator/result copy, 1: thermal TMR copy.",
              "function integer flip_kind(input integer k);",
              f"    flip_kind = (k >= {sum(1 for t in targets if t[0] == 0)}) ? 1 : 0;",
              "endfunction",
              "",
              "// Human-readable name of target k, for the log.",
              "task show_target(input integer k);",
              "    begin",
              "        case (k)"]
    for k, (_kind, rtl, gl) in enumerate(targets):
        lines.append(f"        {k}: $display(\"  target %0d: {rtl[4:]}  <->  cell {gl}\", k);")
    lines += ["        endcase", "    end", "endtask", ""]
    with open(os.path.join(a.out_dir, "gl_inject.vh"), "w") as f:
        f.write("\n".join(lines))
    print(f"gen_gls: {len(targets)} redundant bits mapped to netlist cells; wrote {a.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
