import re, sys
D = sys.argv[1]
out = ["Supplementary multi-corner STA queries, copy-separated sky130hd layout (information only)",
       "Generated by extract_supplement.py from sta_extra_<corner>.log (script work/sta_corners_extra.tcl;",
       "same liberty/odb/sdc/propagated-clock/SPEF setup as pd/sta_corners.tcl). Units: ns, pF.",
       "Path-group slack: worst endpoint per from/to class (report_checks -format end); columns: endpoint, required, actual, slack.",
       "Conditions: build/pd_sep/results/sky130hd/orbit_demo/sep/6_final.{odb,sdc,spef}; period 7.2000 ns, input/output delay 1.4400 ns (6_final.sdc);",
       "OpenRCX SPEF (nominal rules) at every corner; design optimised by ORFS at TT only; image openroad/orfs:latest sha256:2e5bf6fe865e.",
       ""]
for c in ["tt", "ss_100C_1v60", "ff_n40C_1v95"]:
    t = open(f"{D}/sta_extra_{c}.log").read()
    lib = re.search(r"liberty (\S+)", t).group(1)
    out.append(f"corner {c}  ({lib})")
    for m in re.finditer(r"=== (\w+) (max|min) ===\n(.*?)(?==== )", t, re.S):
        row = [l for l in m.group(3).splitlines() if re.search(r"\((MET|VIOLATED)\)", l)]
        out.append(f"  {m.group(1):8s} {'setup' if m.group(2)=='max' else 'hold ':5s} " + (" ".join(row[0].split()) if row else "no path"))
    drv = re.search(r"=== drv ===\n(.*?)=== setup violating", t, re.S).group(1)
    cnt = {}; sec = None
    for l in drv.splitlines():
        if l.startswith("max "): sec = l.strip()
        elif "VIOLATED" in l: cnt[sec] = cnt.get(sec, 0) + 1
    out.append("  DRV violating pins (report_check_types -violators): " + (", ".join(f"{k} {v}" for k, v in cnt.items()) if cnt else "none"))
    sv = re.search(r"=== setup violating endpoints ===\n(.*?)=== hold violating", t, re.S).group(1).count("VIOLATED")
    hv = re.search(r"=== hold violating endpoints ===\n(.*?)=== end", t, re.S).group(1).count("VIOLATED")
    out.append(f"  setup-violating endpoints {sv}; hold-violating endpoints {hv}")
    out.append("")
open(f"{D}/../sta_corners_sep_supplement.txt", "w").write("\n".join(out))
print("\n".join(out))
