// Formal harness for single-event-upset (SEU) injection on generated copies.
//
// Two designs run in lockstep on the same free inputs:
//   dut_r  orbit_demo     the production RTL, fault free (the reference)
//   dut_f  orbit_demo_fi  a copy generated by fault/gen_fault_copies.py in
//                         which one storage element (one per scenario) can
//                         take a bit flip. It has the production port list.
// The scenario (which element, which class of properties) comes from the
// generated fi_scenario.vh; the injection controls of the copy (fi_req of
// every instance of the injected element) from fi_points.vh.
//
// Fault model: at most one upset per trace, in any cycle (including the
// reset cycle), in any lane / bit of the injected element. An upset requested
// in cycle k is stored at the clock edge ending cycle k, so the flipped value
// is visible from cycle k+1 (fi_vis = 1 in that cycle, fi_seen = 1 from then
// on) until the register is written again.
//
// Environment: every input is free; the only constraint is a reset in the
// first cycle. Reset and clear_fault stay free later on.
//
// Property groups (per SymbiYosys task):
//   D_*  data integrity at the ports, all scenarios (the negative scenarios
//        select exactly one of them with -DFI_CHK_FIRE / -DFI_CHK_LOSS)
//   L_*  duplicated lane storage: detection and fault-stop (FI_CLASS_LANE)
//   T_*  thermal copy: masking and repair (FI_CLASS_THERM)
//   H_*  helper invariants that make k-induction close (off with FI_NO_HELPERS)
//   C_*  covers (FI_COVER_TASK; the assertions are then not compiled)
//
// Internal signals are read through Yosys `hierconn` wires, as in
// formal/orbit_demo_fv.sv (needs hierarchy; proc; flatten before any opt;
// `check -assert` fails the run on a wrong path).

`default_nettype none

`include "fi_scenario.vh"

`ifdef FI_COVER_TASK
`elsif FI_CLASS_NEG
`else
`define FI_CHK_FIRE
`define FI_CHK_LOSS
`define FI_CHK_WRONG
`define FI_CHK_EXTRA
`define FI_CHK_BEAT
`endif

module fi_harness (
    input wire        clk,
    input wire        rst_n,
    input wire        in_valid,
    input wire        in_first,
    input wire        in_last,
    input wire [31:0] in_a,
    input wire [31:0] in_b,
    input wire        out_ready,
    input wire        temp_valid,
    input wire [7:0]  temp_c,
    input wire        clear_fault
);

    // ------------------------------------------------------------------
    // Reference (production RTL) and faulty copy, same inputs
    // ------------------------------------------------------------------
    wire         in_ready_r, out_valid_r, fault_r, therm_repair_r, shutdown_req_r;
    wire [127:0] out_data_r;
    wire [1:0]   therm_state_r;
    wire         in_ready_f, out_valid_f, fault_f, therm_repair_f, shutdown_req_f;
    wire [127:0] out_data_f;
    wire [1:0]   therm_state_f;

    orbit_demo dut_r (
        .clk(clk), .rst_n(rst_n), .in_valid(in_valid), .in_ready(in_ready_r),
        .in_first(in_first), .in_last(in_last), .in_a(in_a), .in_b(in_b),
        .out_valid(out_valid_r), .out_ready(out_ready), .out_data(out_data_r),
        .temp_valid(temp_valid), .temp_c(temp_c), .clear_fault(clear_fault),
        .fault(fault_r), .therm_state(therm_state_r), .therm_repair(therm_repair_r),
        .shutdown_req(shutdown_req_r)
    );

    orbit_demo_fi dut_f (
        .clk(clk), .rst_n(rst_n), .in_valid(in_valid), .in_ready(in_ready_f),
        .in_first(in_first), .in_last(in_last), .in_a(in_a), .in_b(in_b),
        .out_valid(out_valid_f), .out_ready(out_ready), .out_data(out_data_f),
        .temp_valid(temp_valid), .temp_c(temp_c), .clear_fault(clear_fault),
        .fault(fault_f), .therm_state(therm_state_f), .therm_repair(therm_repair_f),
        .shutdown_req(shutdown_req_f)
    );

    wire in_fire_r  = in_valid & in_ready_r;
    wire in_fire_f  = in_valid & in_ready_f;
    wire out_fire_r = out_valid_r & out_ready;
    wire out_fire_f = out_valid_f & out_ready;

    // ------------------------------------------------------------------
    // Storage of both designs (SPEC section 7), via hierconn
    // ------------------------------------------------------------------
    (* hierconn *) wire [31:0] \dut_r.g_lane[0].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[1].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[2].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[3].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[0].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[1].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[2].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[3].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[0].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[1].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[2].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[3].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[0].u_lane.u_res_b.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[1].u_lane.u_res_b.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[2].u_lane.u_res_b.q ;
    (* hierconn *) wire [31:0] \dut_r.g_lane[3].u_lane.u_res_b.q ;
    (* hierconn *) wire [1:0]  \dut_r.u_thermal.u_copy0.q ;
    (* hierconn *) wire [1:0]  \dut_r.u_thermal.u_copy1.q ;
    (* hierconn *) wire [1:0]  \dut_r.u_thermal.u_copy2.q ;
    (* hierconn *) wire        \dut_r.u_thermal.phase ;
    (* hierconn *) wire        \dut_r.out_valid_q ;
    (* hierconn *) wire        \dut_r.fault_q ;
    (* hierconn *) wire        \dut_r.mismatch ;
    (* hierconn *) wire        \dut_r.admit ;

    (* hierconn *) wire [31:0] \dut_f.g_lane[0].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[1].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[2].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[3].u_lane.u_acc_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[0].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[1].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[2].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[3].u_lane.u_acc_b.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[0].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[1].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[2].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[3].u_lane.u_res_a.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[0].u_lane.u_res_b.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[1].u_lane.u_res_b.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[2].u_lane.u_res_b.q ;
    (* hierconn *) wire [31:0] \dut_f.g_lane[3].u_lane.u_res_b.q ;
    (* hierconn *) wire [1:0]  \dut_f.u_thermal.u_copy0.q ;
    (* hierconn *) wire [1:0]  \dut_f.u_thermal.u_copy1.q ;
    (* hierconn *) wire [1:0]  \dut_f.u_thermal.u_copy2.q ;
    (* hierconn *) wire        \dut_f.u_thermal.phase ;
    (* hierconn *) wire        \dut_f.out_valid_q ;
    (* hierconn *) wire        \dut_f.fault_q ;
    (* hierconn *) wire        \dut_f.mismatch ;
    (* hierconn *) wire        \dut_f.admit ;

    // Complete state vector, 521 bits, in the order of SPEC section 7:
    //   [127:0] acc_a, [255:128] acc_b, [383:256] res_a, [511:384] res_b
    //   (lane i at 32*i within a group), [513:512] thermal copy 0,
    //   [515:514] copy 1, [517:516] copy 2, [518] phase, [519] out_valid_q,
    //   [520] fault_q.
    wire [520:0] s_r = {
        \dut_r.fault_q , \dut_r.out_valid_q , \dut_r.u_thermal.phase ,
        \dut_r.u_thermal.u_copy2.q , \dut_r.u_thermal.u_copy1.q , \dut_r.u_thermal.u_copy0.q ,
        \dut_r.g_lane[3].u_lane.u_res_b.q , \dut_r.g_lane[2].u_lane.u_res_b.q ,
        \dut_r.g_lane[1].u_lane.u_res_b.q , \dut_r.g_lane[0].u_lane.u_res_b.q ,
        \dut_r.g_lane[3].u_lane.u_res_a.q , \dut_r.g_lane[2].u_lane.u_res_a.q ,
        \dut_r.g_lane[1].u_lane.u_res_a.q , \dut_r.g_lane[0].u_lane.u_res_a.q ,
        \dut_r.g_lane[3].u_lane.u_acc_b.q , \dut_r.g_lane[2].u_lane.u_acc_b.q ,
        \dut_r.g_lane[1].u_lane.u_acc_b.q , \dut_r.g_lane[0].u_lane.u_acc_b.q ,
        \dut_r.g_lane[3].u_lane.u_acc_a.q , \dut_r.g_lane[2].u_lane.u_acc_a.q ,
        \dut_r.g_lane[1].u_lane.u_acc_a.q , \dut_r.g_lane[0].u_lane.u_acc_a.q };
    wire [520:0] s_f = {
        \dut_f.fault_q , \dut_f.out_valid_q , \dut_f.u_thermal.phase ,
        \dut_f.u_thermal.u_copy2.q , \dut_f.u_thermal.u_copy1.q , \dut_f.u_thermal.u_copy0.q ,
        \dut_f.g_lane[3].u_lane.u_res_b.q , \dut_f.g_lane[2].u_lane.u_res_b.q ,
        \dut_f.g_lane[1].u_lane.u_res_b.q , \dut_f.g_lane[0].u_lane.u_res_b.q ,
        \dut_f.g_lane[3].u_lane.u_res_a.q , \dut_f.g_lane[2].u_lane.u_res_a.q ,
        \dut_f.g_lane[1].u_lane.u_res_a.q , \dut_f.g_lane[0].u_lane.u_res_a.q ,
        \dut_f.g_lane[3].u_lane.u_acc_b.q , \dut_f.g_lane[2].u_lane.u_acc_b.q ,
        \dut_f.g_lane[1].u_lane.u_acc_b.q , \dut_f.g_lane[0].u_lane.u_acc_b.q ,
        \dut_f.g_lane[3].u_lane.u_acc_a.q , \dut_f.g_lane[2].u_lane.u_acc_a.q ,
        \dut_f.g_lane[1].u_lane.u_acc_a.q , \dut_f.g_lane[0].u_lane.u_acc_a.q };
    wire [520:0] s_diff = s_f ^ s_r;

    wire [1:0] c0_f = \dut_f.u_thermal.u_copy0.q ;
    wire [1:0] c1_f = \dut_f.u_thermal.u_copy1.q ;
    wire [1:0] c2_f = \dut_f.u_thermal.u_copy2.q ;
    wire [1:0] c0_r = \dut_r.u_thermal.u_copy0.q ;
    wire [1:0] c1_r = \dut_r.u_thermal.u_copy1.q ;
    wire [1:0] c2_r = \dut_r.u_thermal.u_copy2.q ;
    wire       mismatch_f = \dut_f.mismatch ;
    wire       admit_f    = \dut_f.admit ;
    wire       admit_r    = \dut_r.admit ;

    // The faulty copy has stopped: a latched fault or a copy disagreement
    // this cycle (either one forces in_ready = out_valid = 0, SPEC section 5).
    wire stopped_f = fault_f | mismatch_f;

`ifdef FI_TARGET_GROUP
    // Bits of the state vector that belong to the injected element.
    localparam [520:0] ONES128 = {{393{1'b0}}, {128{1'b1}}};
    localparam [520:0] ONES2   = {{519{1'b0}}, 2'b11};
    localparam [520:0] ONE1    = {{520{1'b0}}, 1'b1};
    localparam [520:0] FI_TMASK =
        (`FI_TARGET_GROUP <= 3) ? (ONES128 << (128 * `FI_TARGET_GROUP)) :
        (`FI_TARGET_GROUP <= 6) ? (ONES2 << (512 + 2 * (`FI_TARGET_GROUP - 4))) :
                                  (ONE1 << (518 + `FI_TARGET_GROUP - 7));
    localparam [520:0] FI_TMASK_LO = FI_TMASK & ~(FI_TMASK << 1);   // lane 0 bit 0 / copy bit 0
    localparam [520:0] FI_TMASK_HI = FI_TMASK & ~(FI_TMASK >> 1);   // lane 3 bit 31 / copy bit 1
`endif

    // ------------------------------------------------------------------
    // Single-upset fault model
    // ------------------------------------------------------------------
    `include "fi_points.vh"

    wire fi_fire = |fi_req_vec;
    reg  fi_seen = 1'b0;    // the upset has been stored (from its first visible cycle on)
    reg  fi_vis  = 1'b0;    // first cycle in which the flipped value is visible
    always @(posedge clk) begin
        fi_seen <= fi_seen | fi_fire;
        fi_vis  <= fi_fire;
    end
    always @* begin
        // One injection point per cycle, one upset per trace.
        assume ((fi_req_vec & (fi_req_vec - 1'b1)) == 0);
        if (fi_seen)
            assume (!fi_fire);
    end

    // ------------------------------------------------------------------
    // Environment
    // ------------------------------------------------------------------
    reg f_past_valid = 1'b0;
    always @(posedge clk)
        f_past_valid <= 1'b1;
    always @* begin
        if (!f_past_valid)
            assume (!rst_n);
    end

`ifndef FI_COVER_TASK
    // ------------------------------------------------------------------
    // D: data integrity at the ports (every scenario)
    // ------------------------------------------------------------------
    always @* begin
        if (f_past_valid) begin
`ifdef FI_CHK_FIRE
            // Headline: every result the faulty copy transfers is transferred
            // by the reference in the same cycle, with identical data.
            if (out_fire_f) begin
                D_out_fire_matches_ref: assert (out_fire_r && out_data_f == out_data_r);
            end
`endif
`ifdef FI_CHK_WRONG
            // Stronger: whatever both present is identical.
            if (out_valid_f && out_valid_r) begin
                D_no_wrong_result: assert (out_data_f == out_data_r);
            end
`endif
`ifdef FI_CHK_EXTRA
            // The faulty copy never presents a result the reference does not.
            if (out_valid_f) begin
                D_no_extra_result: assert (out_valid_r);
            end
`endif
`ifdef FI_CHK_LOSS
            // A result the reference presents is withheld only by a stop.
            if (out_valid_r && !out_valid_f) begin
                D_no_silent_loss: assert (stopped_f);
            end
`endif
`ifdef FI_CHK_BEAT
            // Input admission differs from the reference only by a stop.
            if (in_ready_f != in_ready_r) begin
                D_no_silent_beat_divergence: assert (stopped_f && !in_ready_f);
            end
`endif
        end
    end
`endif

`ifndef FI_COVER_TASK
`ifdef FI_CLASS_LANE
    // ------------------------------------------------------------------
    // L: an upset in one copy of accumulator / result storage
    // ------------------------------------------------------------------
    always @* begin
        if (f_past_valid) begin
            // Before the upset the copy is the reference, bit for bit.
            if (!fi_seen) begin
                L_lockstep_before_upset: assert (s_f == s_r);
            end
            // The generated copy flips exactly one bit, inside the target.
            if (fi_vis) begin
                L_single_bit_in_target: assert (s_diff != 0 && (s_diff & (s_diff - 1'b1)) == 0 &&
                                                (s_diff & ~FI_TMASK) == 0);
                // Same cycle: the copies disagree and both handshakes drop.
                L_stop_in_upset_cycle: assert (mismatch_f && !in_ready_f && !out_valid_f);
            end
            // A stop blocks both sides (SPEC section 5).
            if (stopped_f) begin
                L_stop_blocks: assert (!in_ready_f && !out_valid_f);
            end
            // No false alarm: fault and stop only ever follow the upset.
            if (stopped_f) begin
                L_stop_only_after_upset: assert (fi_seen);
            end
            // The thermal part is untouched by a lane upset.
            L_thermal_unaffected: assert (therm_state_f == therm_state_r && therm_repair_f == therm_repair_r &&
                                          shutdown_req_f == shutdown_req_r && admit_f == admit_r);
        end
    end

    always @(posedge clk) begin
        if (f_past_valid) begin
            // fault rises one cycle after the upset-visible cycle, unless reset or
            // clear_fault is asserted in that cycle ...
            if ($past(fi_vis) && $past(rst_n) && !$past(clear_fault)) begin
                L_fault_next_cycle: assert (fault_f);
            end
            // ... in which case the flipped copy has been overwritten (zeroed or
            // reset together with its partner) before it could be used: no
            // fault, and the copy is the reference again, bit for bit.
            if ($past(fi_vis) && (!$past(rst_n) || $past(clear_fault))) begin
                L_overwritten_no_fault: assert (!fault_f && s_f == s_r);
            end
            // fault is sticky until reset / clear_fault.
            if ($past(fault_f) && $past(rst_n) && !$past(clear_fault)) begin
                L_fault_sticky: assert (fault_f);
            end
            // reset / clear_fault always resynchronise the copy with the
            // reference (unless the single upset lands in that very edge).
            if ((!$past(rst_n) || $past(clear_fault)) && !fi_vis) begin
                L_resync_after_clear: assert (s_f == s_r && !fault_f);
            end
        end
    end

`ifndef FI_NO_HELPERS
    always @* begin
        if (f_past_valid) begin
            // The reference is fault free (SPEC section 5; formal area P7).
            H_ref_copies_equal: assert (s_r[127:0] == s_r[255:128] && s_r[383:256] == s_r[511:384] &&
                                        c0_r == c1_r && c1_r == c2_r && !\dut_r.fault_q );
            if (fi_vis) begin
                H_vis_seen: assert (fi_seen);
            end
            // After the upset cycle: back in lockstep, or stopped with a latched
            // fault while the thermal part still follows the reference.
            if (fi_seen && !fi_vis) begin
                H_after_upset: assert (s_f == s_r || (\dut_f.fault_q && s_f[518:512] == s_r[518:512]));
            end
        end
    end
`endif
`endif
`endif

`ifndef FI_COVER_TASK
`ifdef FI_CLASS_THERM
    // ------------------------------------------------------------------
    // T: an upset in one thermal state copy
    // ------------------------------------------------------------------
    always @* begin
        if (f_past_valid) begin
            if (!fi_seen) begin
                T_lockstep_before_upset: assert (s_f == s_r);
            end
            if (fi_vis) begin
                T_single_bit_in_target: assert (s_diff != 0 && (s_diff & (s_diff - 1'b1)) == 0 &&
                                                (s_diff & ~FI_TMASK) == 0);
            end
            // Voted state and admission equal the reference in every cycle.
            T_voted_state_equal: assert (therm_state_f == therm_state_r);
            T_admission_equal:   assert (admit_f == admit_r && in_ready_f == in_ready_r);
            // Nothing else is visible at the ports either (no fault stop).
            T_other_ports_equal: assert (out_valid_f == out_valid_r && out_data_f == out_data_r &&
                                         fault_f == fault_r && shutdown_req_f == shutdown_req_r);
            // therm_repair is high exactly while the copies disagree ...
            T_repair_iff_disagree: assert (therm_repair_f == !(c0_f == c1_f && c1_f == c2_f));
            // ... which is exactly the upset-visible cycle.
            T_repair_only_upset_cycle: assert (therm_repair_f == fi_vis);
            // From the cycle after the upset on, everything equals the reference.
            if (fi_seen && !fi_vis) begin
                T_repaired_after_upset: assert (s_f == s_r);
            end
        end
    end

    always @(posedge clk) begin
        if (f_past_valid && $past(fi_vis)) begin
            // One cycle later the upset copy equals the other two again.
            T_copy_rewritten_next_cycle: assert (c0_f == c1_f && c1_f == c2_f && c0_f == c0_r);
        end
    end

`ifndef FI_NO_HELPERS
    always @* begin
        if (f_past_valid) begin
            H_ref_copies_equal: assert (s_r[127:0] == s_r[255:128] && s_r[383:256] == s_r[511:384] &&
                                        c0_r == c1_r && c1_r == c2_r && !\dut_r.fault_q );
            if (fi_vis) begin
                H_vis_seen: assert (fi_seen);
            end
        end
    end
`endif
`endif
`endif

`ifdef FI_COVER_TASK
    // ------------------------------------------------------------------
    // Covers: the upset situations the proofs talk about are reachable
    // ------------------------------------------------------------------
    reg f_had_fault = 1'b0;
    always @(posedge clk) begin
        if (fault_f)
            f_had_fault <= 1'b1;
    end

    always @(posedge clk) begin
        if (f_past_valid) begin
            C_upset_visible:      cover (fi_vis);
`ifdef FI_TARGET_GROUP
            C_upset_lowest_bit:   cover (fi_vis && s_diff == FI_TMASK_LO);
            C_upset_highest_bit:  cover (fi_vis && s_diff == FI_TMASK_HI);
`endif
`ifdef FI_CLASS_LANE
            // The upset blocks a result the reference transfers in that cycle ...
            C_upset_blocks_result: cover (fi_vis && out_valid_r && out_ready);
            // ... and a beat the reference accepts.
            C_upset_blocks_beat:   cover (fi_vis && in_valid && in_ready_r);
            C_fault_latched:       cover (fault_f);
            // The overwritten case: clear_fault in the upset-visible cycle.
            C_overwritten_by_clear: cover ($past(fi_vis) && $past(clear_fault) && $past(rst_n));
            // After fault and clear_fault, results flow again.
            C_result_after_recovery: cover (f_had_fault && out_fire_f && !fault_f);
`endif
`ifdef FI_CLASS_THERM
            C_upset_in_normal_with_beat: cover (fi_vis && therm_state_r == 2'd0 && in_fire_f);
            C_upset_in_throttle:         cover (fi_vis && therm_state_r == 2'd1);
            C_upset_in_stop:             cover (fi_vis && therm_state_r == 2'd2);
            // The upset copy reads the unused code 3.
            C_upset_copy_code3:          cover (fi_vis && (s_f & FI_TMASK) == FI_TMASK);
            C_upset_during_transfer:     cover (fi_vis && out_fire_f);
`endif
`ifdef FI_CLASS_NEG
            C_result_transferred:  cover (out_fire_f && fi_seen);
`endif
        end
    end
`endif

endmodule

`default_nettype wire
