#!/usr/bin/env python3
"""Summarise an ORFS clock-period sweep of orbit_demo.

Each sweep point is one complete ORFS run (synthesis to the final report with
OpenRCX parasitics) in its own FLOW_VARIANT, p<period>ns. A point "closes" when
the final setup and hold worst slacks are >= 0, the TNS values are 0, the
detailed router reports 0 DRC errors and there are no slew/cap/fanout
violations. Timing is at the single liberty corner the ORFS platform uses.

Writes a Markdown table and prints the best (shortest) closing period and the
first failing one below it.
"""

import argparse
import json
import os
import sys


def load(path):
    try:
        with open(path) as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--work", required=True)
    ap.add_argument("--platform", default="sky130hd")
    ap.add_argument("--design", default="orbit_demo")
    ap.add_argument("--periods", required=True, help="space separated periods in ns")
    ap.add_argument("--corner", default="", help="text describing the timing corner")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    rows = []
    for p in a.periods.split():
        var = f"p{p}ns"
        logs = os.path.join(a.work, "logs", a.platform, a.design, var)
        fin = load(os.path.join(logs, "6_report.json"))
        drt = load(os.path.join(logs, "5_2_route.json")) or {}
        if not fin:
            rows.append({"period": float(p), "variant": var, "status": "NO RESULT"})
            continue
        g = lambda k: fin.get("finish__" + k)
        drc = drt.get("detailedroute__route__drc_errors")
        drv = sum((g(k) or 0) for k in ("timing__drv__max_slew", "timing__drv__max_cap", "timing__drv__max_fanout"))
        closed = (g("timing__setup__ws") is not None and g("timing__setup__ws") >= 0 and
                  g("timing__hold__ws") is not None and g("timing__hold__ws") >= 0 and
                  (g("timing__setup__tns") or 0) == 0 and (g("timing__hold__tns") or 0) == 0 and
                  drc == 0 and drv == 0)
        rows.append({
            "period": float(p), "variant": var,
            "setup_ws": g("timing__setup__ws"), "setup_tns": g("timing__setup__tns"),
            "hold_ws": g("timing__hold__ws"), "hold_tns": g("timing__hold__tns"),
            "fmax_mhz": (g("timing__fmax") or 0) / 1e6, "drc": drc, "drv": drv,
            "area": g("design__instance__area__stdcell"), "util": g("design__instance__utilization"),
            "power": g("power__total"),
            "status": "CLOSED" if closed else "FAILS",
        })

    rows.sort(key=lambda r: -r["period"])
    closed = [r for r in rows if r["status"] == "CLOSED"]
    best = min(closed, key=lambda r: r["period"]) if closed else None
    first_fail = None
    if best:
        below = [r for r in rows if r["period"] < best["period"] and r["status"] != "CLOSED"]
        first_fail = max(below, key=lambda r: r["period"]) if below else None

    f3 = lambda v: "n/a" if v is None else f"{v:.3f}"
    lines = [f"# Clock-period sweep: {a.design} on {a.platform}", "",
             "Generated by pd/sweep_summary.py. One full ORFS run per period (synthesis",
             "through detailed route and the final OpenRCX-extracted STA), NUM_CORES=2.",
             f"Timing corner: {a.corner}" if a.corner else "", "",
             "| Period (ns) | Target (MHz) | Setup WNS (ns) | Setup TNS (ns) | Hold WNS (ns) | Hold TNS (ns) "
             "| STA fmax (MHz) | Route DRC | Slew/cap/fanout viol. | Cell area (um^2) | Util. | Power (mW, default activity) | Status |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        if "setup_ws" not in r:
            lines.append(f"| {r['period']:g} | {1000 / r['period']:.1f} | | | | | | | | | | | {r['status']} |")
            continue
        lines.append(f"| {r['period']:g} | {1000 / r['period']:.1f} | {f3(r['setup_ws'])} | {f3(r['setup_tns'])} | "
                     f"{f3(r['hold_ws'])} | {f3(r['hold_tns'])} | {r['fmax_mhz']:.1f} | {r['drc']} | {r['drv']} | "
                     f"{r['area']:.0f} | {r['util']:.3f} | {r['power'] * 1e3:.2f} | {r['status']} |")
    lines.append("")
    if best:
        lines.append(f"Best closed period: **{best['period']:g} ns ({1000 / best['period']:.1f} MHz)**.")
    else:
        lines.append("No period in the sweep closed timing.")
    if first_fail:
        lines.append(f"First failing period below it: **{first_fail['period']:g} ns "
                     f"({1000 / first_fail['period']:.1f} MHz)**, setup WNS {f3(first_fail.get('setup_ws'))} ns, "
                     f"hold WNS {f3(first_fail.get('hold_ws'))} ns.")
    elif best:
        lines.append("No failing period below the best closed one was run.")
    lines += ["", "STA fmax is OpenROAD's report_clock_min_period -include_port_paths on the final",
              "design at that run's constraints; it is not a guarantee at a different period, because",
              "every run re-optimises for its own target."]
    text = "\n".join(l for l in lines) + "\n"
    with open(a.out, "w") as fh:
        fh.write(text)
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
