#!/usr/bin/env python3
"""Hsiao (72,64) SECDED parity-check matrix for rtl/ecc/orbit_secded72.v.

Construction (Hsiao 1970, odd-weight-column code):
  * check bit j  (codeword bit 64+j): unit column e_j (weight 1)
  * data bits 0..55: all C(8,3) = 56 weight-3 columns, lexicographic order of
    the row triple (r0 < r1 < r2)
  * data bits 56..63: the weight-5 pattern 0b00011111 rotated left by 0..7

Each row of the 8 x 64 data part then has 21 + 5 = 26 ones (27 with its check
bit), so the eight parity trees are the same size.

Why this is SECDED: all 72 columns are distinct, non-zero and of odd weight.
A single error gives the (odd) syndrome of exactly one column; a double error
gives the XOR of two distinct odd columns, which is non-zero and of even
weight, so it can never equal a column and is never miscorrected.

Usage:
  gen_hsiao72.py            print the Verilog localparam block
  gen_hsiao72.py --check F  verify that Verilog file F contains exactly that
                            block and that the matrix has the Hsiao properties;
                            exit status 1 on any mismatch
"""

import argparse
import itertools
import re
import sys

N_DATA = 64
N_CHECK = 8


def data_columns():
    """The 64 data columns as 8-bit integers (bit r = row r)."""
    cols = [(1 << a) | (1 << b) | (1 << c)
            for a, b, c in itertools.combinations(range(N_CHECK), 3)]
    base = 0b00011111
    for k in range(N_CHECK):
        cols.append(((base << k) | (base >> (N_CHECK - k))) & 0xFF)
    assert len(cols) == N_DATA
    return cols


def row_masks(cols):
    """Row r as a 64-bit mask over the data bits."""
    return [sum(((c >> r) & 1) << i for i, c in enumerate(cols)) for r in range(N_CHECK)]


def check_properties(cols):
    """Return a list of violated Hsiao properties (empty if the matrix is good)."""
    errors = []
    all_cols = cols + [1 << j for j in range(N_CHECK)]
    if len(set(all_cols)) != len(all_cols):
        errors.append("columns are not distinct")
    if any(c == 0 for c in all_cols):
        errors.append("zero column")
    if any(bin(c).count("1") % 2 == 0 for c in all_cols):
        errors.append("even-weight column")
    weights = [bin(m).count("1") for m in row_masks(cols)]
    if len(set(weights)) != 1:
        errors.append("unbalanced data row weights %s" % weights)
    return errors


def verilog_block(cols):
    lines = ["    // BEGIN generated by rtl/ecc/gen_hsiao72.py (do not edit by hand)",
             "    // H_ROW<r>: data bits that feed check bit r (26 ones per row)."]
    for r, m in enumerate(row_masks(cols)):
        lines.append("    localparam [63:0] H_ROW%d = 64'h%016x;" % (r, m))
    lines.append("    // END generated")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", metavar="VERILOG", help="verify the block in this file")
    args = ap.parse_args()

    cols = data_columns()
    problems = check_properties(cols)
    if problems:
        print("gen_hsiao72: construction broken: " + "; ".join(problems))
        return 1
    block = verilog_block(cols)
    if not args.check:
        print(block)
        return 0

    text = open(args.check).read()
    found = re.search(r"^ *// BEGIN generated.*?// END generated", text, re.S | re.M)
    if not found:
        print("gen_hsiao72: FAIL: no generated block in %s" % args.check)
        return 1
    if found.group(0).strip() != block.strip():
        print("gen_hsiao72: FAIL: H matrix in %s differs from the Hsiao construction" % args.check)
        return 1
    weights = [bin(m).count("1") for m in row_masks(cols)]
    print("gen_hsiao72: PASS: %s holds the Hsiao (72,64) matrix: 72 distinct odd-weight "
          "columns (56 x w3, 8 x w5, 8 x w1), data row weights %s" % (args.check, weights[0]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
