// ORBIT-AI ECC extension: (72,64) SECDED Hsiao code, encoder and decoder.
//
// Target-architecture item "Protected SRAM / SECDED ECC + interleaving"
// (docs/orbit-ai-design-brief.pdf, page 1): 64 data bits + 8 check bits.
// Not part of the built demonstrator (orbit_demo); see rtl/ecc/README.md.
//
// Codeword layout: cw[63:0] = data, cw[71:64] = check bits.
//
// The parity-check matrix H is a Hsiao odd-weight-column matrix (generator
// and property check: rtl/ecc/gen_hsiao72.py). All 72 columns are distinct
// and of odd weight, so
//   * no error      -> syndrome 0
//   * single error  -> syndrome equals exactly one column: corrected, ce = 1
//   * double error  -> syndrome non-zero with even weight, equal to no
//                      column: nothing is flipped, ue = 1
//   * three or more -> not guaranteed (may be miscorrected or flagged ue)
//
// Both modules are purely combinational. H is defined once, in the encoder;
// the decoder computes its syndrome with an encoder instance and obtains the
// error-locator column of data bit i by encoding the unit vector 1 << i (a
// constant that synthesis folds away), so encoder and decoder cannot use
// different matrices.

`default_nettype none

// This file holds the two codec modules (orbit_secded72_enc/_dec) on purpose.
/* verilator lint_off DECLFILENAME */

module orbit_secded72_enc (
    input  wire [63:0] data,
    output wire [7:0]  check
);

    // BEGIN generated by rtl/ecc/gen_hsiao72.py (do not edit by hand)
    // H_ROW<r>: data bits that feed check bit r (26 ones per row).
    localparam [63:0] H_ROW0 = 64'hf1000000001fffff;
    localparam [63:0] H_ROW1 = 64'he300000fffe0003f;
    localparam [63:0] H_ROW2 = 64'hc7003ff003e007c1;
    localparam [63:0] H_ROW3 = 64'h8f0fc0f03c207842;
    localparam [63:0] H_ROW4 = 64'h1f71c711c4438884;
    localparam [63:0] H_ROW5 = 64'h3eb65926488c9108;
    localparam [63:0] H_ROW6 = 64'h7cdaaa4a91152210;
    localparam [63:0] H_ROW7 = 64'hf8ed348d221a4420;
    // END generated

    // Even parity per row: check[r] ^ (XOR of the data bits in row r) == 0.
    assign check = {^(data & H_ROW7), ^(data & H_ROW6), ^(data & H_ROW5), ^(data & H_ROW4),
                    ^(data & H_ROW3), ^(data & H_ROW2), ^(data & H_ROW1), ^(data & H_ROW0)};

endmodule


module orbit_secded72_dec (
    input  wire [63:0] data_in,    // received data bits   (cw[63:0])
    input  wire [7:0]  check_in,   // received check bits  (cw[71:64])
    output wire [63:0] data_out,   // corrected data (raw data_in when ue)
    output wire [7:0]  check_out,  // corrected check bits (raw check_in when ue)
    output wire        ce,         // exactly one bit was in error and has been corrected
    output wire        ue,         // uncorrectable: non-zero syndrome matching no column
    output wire [7:0]  syndrome    // H * cw; 0 means no error detected
);

    wire [7:0] check_calc;

    orbit_secded72_enc u_syn (.data(data_in), .check(check_calc));

    assign syndrome = check_calc ^ check_in;

    // One comparator per codeword bit: which single-bit error explains the syndrome.
    wire [63:0] hit_data;
    wire [7:0]  hit_check;

    genvar i;
    generate
        for (i = 0; i < 64; i = i + 1) begin : g_data_col
            wire [7:0] col;   // column i of H (constant)
            orbit_secded72_enc u_col (.data(64'd1 << i), .check(col));
            assign hit_data[i] = (syndrome == col);
        end
        for (i = 0; i < 8; i = i + 1) begin : g_check_col
            assign hit_check[i] = (syndrome == (8'd1 << i));
        end
    endgenerate

    // At most one hit bit is set because the columns are distinct.
    assign data_out  = data_in ^ hit_data;
    assign check_out = check_in ^ hit_check;
    assign ce        = |{hit_data, hit_check};
    assign ue        = (syndrome != 8'd0) & ~ce;

endmodule

/* verilator lint_on DECLFILENAME */

`default_nettype wire
