# Simulation (area: sim): self-checking simulation of orbit_demo under Icarus
# Verilog and Verilator, and a cocotb constrained-random test against an
# independent Python model of docs/SPEC.md.
# Owner: sim area (tb/ except tb/ecc/, mk/sim.mk, reports/sim/).
#
#   make sim            sim-model, sim-directed, sim-verilator, sim-random,
#                       sim-random-verilator and sim-gls (about 2 minutes);
#                       part of TEST_TARGETS
#   make sim-model      self-test of the Python reference model tb/cocotb/orbit_ref.py
#   make sim-directed   directed bench tb/tb_orbit_demo.v on $(RTL), Icarus Verilog
#   make sim-verilator  the same bench built by Verilator --binary --timing; its
#                       summary must equal the Icarus summary line for line
#   make sim-random     cocotb random test (tb/cocotb/) under Icarus: SIM_SEEDS x
#                       SIM_CYCLES cycles plus an INT32 wraparound soak, checked every
#                       cycle, with functional coverage that must be non-zero
#   make sim-random-verilator
#                       the cocotb random test under Verilator for SIM_VL_SEEDS; every
#                       coverage count must equal the Icarus run of the same seed
#   make sim-gls        the directed bench on a gate-level netlist. SIM_GLS_SRCS lists
#                       the netlist (top module orbit_demo, same ports) and its cell
#                       models; empty = a Yosys generic netlist of $(RTL). Example, the
#                       routed sky130hd netlist of the pd area:
#                         make sim-gls SIM_GLS_TAG=sky130hd SIM_GLS_SRCS="$(BUILD)/pd/results/sky130hd/orbit_demo/base/6_final.v $(BUILD)/pd/gls/sky130hd/cells.v"
#   make sim-mutants    negative control: both benches must FAIL on every deliberately
#                       broken copy of $(RTL) generated by tb/sim_mutants.py (not in `sim`)
#   make sim-report     sim + sim-mutants, then write $(SIM_REPORT_DIR)/summary.md and
#                       copy the logs there (only when RTL_DIR is the production rtl/)
#
# Outputs go to $(BUILD)/sim/. Everything runs against $(RTL), so
# `make RTL_DIR=<copy> BUILD=<dir> sim` checks a modified copy of the RTL.

SIM_OUT         := $(BUILD)/sim
SIM_TB          := tb/tb_orbit_demo.v
SIM_PY          ?= tabbypy3
SIM_SEED        ?= 1
SIM_SEEDS       ?= 1 2 3 4 5
SIM_CYCLES      ?= 20000
SIM_SOAK_SEEDS  ?= 1
SIM_SOAK_MAX    ?= 400000
SIM_VL_SEEDS    ?= 1 2
SIM_JOBS        ?= 2
SIM_IVERILOG    ?= iverilog -g2005 -Wall -Wno-timescale
# The bench runs in about a second either way; -O0 only shortens the C++ build.
SIM_VL_OPT      ?= OPT_FAST=-O0 OPT_SLOW=-O0 OPT_GLOBAL=-O0
SIM_GLS_SRCS    ?=
SIM_GLS_FLAGS   ?=
SIM_GLS_TAG     ?= $(if $(strip $(SIM_GLS_SRCS)),custom,yosys)
SIM_GLS_DIR      = $(SIM_OUT)/gls/$(SIM_GLS_TAG)
SIM_GLS_NETLIST  = $(if $(strip $(SIM_GLS_SRCS)),$(SIM_GLS_SRCS),$(SIM_GLS_DIR)/orbit_demo_yosys.v)
SIM_MUT_CYCLES  ?= 20000
SIM_REPORT_DIR  ?= reports/sim
SIM_PUBLISH     ?= $(if $(filter rtl rtl/ ./rtl,$(RTL_DIR)),$(SIM_REPORT_DIR))

# The summary block the directed bench prints; identical stimulus must give an
# identical block on every simulator and on any correct netlist.
SIM_SUMMARY_OF   = sed -n '/^tb_orbit_demo summary/,/^TB_ORBIT_DEMO/p' $(1)

SIM_RANDOM_RUN   = $(SIM_PY) tb/cocotb/run_random.py --jobs $(SIM_JOBS) --sources $(RTL) \
                   --cycles $(SIM_CYCLES) --soak-max $(SIM_SOAK_MAX)

.PHONY: sim sim-model sim-directed sim-verilator sim-random sim-random-verilator \
        sim-gls sim-mutants sim-report

sim: sim-model sim-directed sim-verilator sim-random sim-random-verilator sim-gls
	@echo "SIM PASS: model self-test, directed (Icarus + Verilator), cocotb random (Icarus + Verilator), gate-level ($(SIM_GLS_TAG))"

sim-model:
	@mkdir -p $(SIM_OUT)
	set -o pipefail; python3 tb/cocotb/orbit_ref.py | tee $(SIM_OUT)/model.log

sim-directed:
	@mkdir -p $(SIM_OUT)/directed
	$(SIM_IVERILOG) -o $(SIM_OUT)/directed/tb.vvp $(SIM_TB) $(RTL)
	set -o pipefail; vvp -n $(SIM_OUT)/directed/tb.vvp +seed=$(SIM_SEED) | tee $(SIM_OUT)/directed/icarus.log
	@grep -q '^TB_ORBIT_DEMO PASS' $(SIM_OUT)/directed/icarus.log

sim-verilator: sim-directed
	@mkdir -p $(SIM_OUT)/verilator
	@echo "verilator --binary --timing ... $(SIM_TB) $(RTL)  (log: $(SIM_OUT)/verilator/build.log)"
	@verilator --binary --timing -j $(SIM_JOBS) --top-module tb_orbit_demo \
	    --Mdir $(SIM_OUT)/verilator/obj_dir -o Vtb_orbit_demo -MAKEFLAGS "$(SIM_VL_OPT)" \
	    $(SIM_TB) $(RTL) > $(SIM_OUT)/verilator/build.log 2>&1 \
	    || { tail -40 $(SIM_OUT)/verilator/build.log; echo "sim-verilator: build FAILED"; exit 1; }
	set -o pipefail; $(SIM_OUT)/verilator/obj_dir/Vtb_orbit_demo +seed=$(SIM_SEED) | tee $(SIM_OUT)/verilator/verilator.log
	@grep -q '^TB_ORBIT_DEMO PASS' $(SIM_OUT)/verilator/verilator.log
	@diff <($(call SIM_SUMMARY_OF,$(SIM_OUT)/directed/icarus.log)) \
	      <($(call SIM_SUMMARY_OF,$(SIM_OUT)/verilator/verilator.log)) \
	    && echo "sim-verilator: summary identical to Icarus" \
	    || { echo "sim-verilator: summary differs from Icarus"; exit 1; }

sim-random: sim-model
	@mkdir -p $(SIM_OUT)/random
	set -o pipefail; $(SIM_RANDOM_RUN) --sim icarus --out $(SIM_OUT)/random \
	    --seeds $(SIM_SEEDS) --soak-seeds $(SIM_SOAK_SEEDS) 2>&1 | tee $(SIM_OUT)/random/run.log

sim-random-verilator: sim-random
	@mkdir -p $(SIM_OUT)/random_verilator
	set -o pipefail; $(SIM_RANDOM_RUN) --sim verilator --out $(SIM_OUT)/random_verilator \
	    --seeds $(SIM_VL_SEEDS) --soak-seeds --compare-with $(SIM_OUT)/random \
	    2>&1 | tee $(SIM_OUT)/random_verilator/run.log

sim-gls: sim-directed
	@mkdir -p $(SIM_GLS_DIR)
	@if [ -z "$(strip $(SIM_GLS_SRCS))" ]; then \
	    echo "yosys: generic gate-level netlist of $(RTL) -> $(SIM_GLS_DIR)/orbit_demo_yosys.v"; \
	    yosys -q -l $(SIM_GLS_DIR)/yosys.log -p "read_verilog $(RTL); synth -flatten -top $(TOP); \
	        stat; write_verilog -noattr $(SIM_GLS_DIR)/orbit_demo_yosys.v" || exit 1; \
	fi
	$(SIM_IVERILOG) $(SIM_GLS_FLAGS) -o $(SIM_GLS_DIR)/tb.vvp $(SIM_TB) $(SIM_GLS_NETLIST) \
	    > $(SIM_GLS_DIR)/compile.log 2>&1 || { cat $(SIM_GLS_DIR)/compile.log; exit 1; }
	set -o pipefail; vvp -n $(SIM_GLS_DIR)/tb.vvp +seed=$(SIM_SEED) | tee $(SIM_GLS_DIR)/gls.log
	@grep -q '^TB_ORBIT_DEMO PASS' $(SIM_GLS_DIR)/gls.log
	@diff <($(call SIM_SUMMARY_OF,$(SIM_OUT)/directed/icarus.log)) \
	      <($(call SIM_SUMMARY_OF,$(SIM_GLS_DIR)/gls.log)) \
	    && echo "sim-gls: summary identical to the RTL run" \
	    || { echo "sim-gls: summary differs from the RTL run"; exit 1; }

sim-mutants:
	@mkdir -p $(SIM_OUT)/mutants
	set -o pipefail; python3 tb/sim_mutants.py --rtl-dir $(RTL_DIR) --out $(SIM_OUT)/mutants \
	    --tb $(SIM_TB) --cocotb-python $(SIM_PY) --random-cycles $(SIM_MUT_CYCLES) \
	    --jobs $(SIM_JOBS) | tee $(SIM_OUT)/mutants/run.log

sim-report: sim sim-mutants
	@if [ -z "$(SIM_PUBLISH)" ]; then \
	    echo "sim-report: RTL_DIR=$(RTL_DIR) is not the production rtl/; nothing copied to reports/"; \
	else \
	    python3 tb/sim_report.py --build $(SIM_OUT) --out $(SIM_PUBLISH) --rtl "$(RTL)" \
	        --seed $(SIM_SEED) --seeds "$(SIM_SEEDS)" --cycles $(SIM_CYCLES) \
	        --soak-seeds "$(SIM_SOAK_SEEDS)" --soak-max $(SIM_SOAK_MAX) --vl-seeds "$(SIM_VL_SEEDS)" \
	        --mut-cycles $(SIM_MUT_CYCLES) --vl-opt "$(SIM_VL_OPT)" --jobs $(SIM_JOBS) \
	    && echo "sim-report: wrote $(SIM_PUBLISH)/summary.md"; \
	fi

TEST_TARGETS += sim
